### ISSUE TITLE
Are you planning to upload more codes?

### ISSUE THREAD

**Issue by Flitternie** [yangliuy/HybridNCM#1]
Dear Liu Yang,

Recently I read your paper "A Hybrid Retrieval-Generation Neural Conversation Model" and was quite impressed. I plan to reproduce your works and noticed that your codes are not uploaded yet.

Would you mind upload more files so I can reproduce your fantastic works? Really appreciate if that is possible. Thanks.

Flitter

**Comment by yangliuy** [comment]
Dear Flitter,

Thank you for your interests on our work!

Yes, I will update more code files into this repository. Unfortunately, I can not open source the experimental data sets (the Twitter & Foursquare data) used in our paper since they are internal data sets from Microsoft Research. But I hope the code we upload here will provide a reference for you to implement the key components of our proposed model like Seq2Seq, Seq2Seq-Facts and the hybrid ranking module, etc. We will also upload some demo data from other conversation data sets for demo/testing purpose. Stay tuned.

Thanks
Best
Liu

**Comment by Flitternie** [comment]
Dear Liu,

Thanks for your reply!
Would you mind update the hybrid ranking part so I can take it as a baseline in a retrieval-based matching network research project that I am working on?
Really appreciate if that is possible.

Thanks,
Flitter

**Comment by yangliuy** [comment]
Dear Flitter,

Yes, we will update the code later. You could watch the updates from this repository.

Best
Liu
